### ISSUE TITLE
Display license when installing as plugin

### ISSUE THREAD

**Issue by hame-c8y** [Cumulocity-IoT/cumulocity-dynamic-mapper#275]
At the moment it looks like the license cannot be properly shown:

![image](https://github.com/user-attachments/assets/506ecffc-9017-4938-85da-71d8498d94c9)

**Comment by switschel** [comment]
This is because the LICENSE is in the root folder and not in the plugin folder. I fixed it in the build workflow but when locally build the LICENSE is still not part of the archive.
@ck-c8y Maybe you have a idea how to fix this in the package.json etc.? We should not duplicate the license because if doing to we need to maintain it in two locations which is not very nice.

**Comment by switschel** [comment]
Also we should stick to the Apache-2.0 license as it is the main license in the whole project

**Comment by ck-c8y** [comment]
@switschel: Could you pls. verify if this 44606ee2e14f8f9635c5f39796d183abdcbfa251 fixes the issue?
